-- Creates sms_messages table used by the admin UI (adjust types if needed)
create table if not exists public.sms_messages (
  id bigint generated by default as identity primary key,
  student_id text,
  recipient text,
  phone text,
  message text,
  template text,
  sent_at timestamptz default now(),
  status text, -- e.g. 'intent_created', 'sent', 'failed'
  gateway_response text,
  created_at timestamptz default now()
);
